apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/deployment.yaml
  - base/service.yaml

nameSuffix: -develop
namespace: default

commonLabels:
  app: v2ray-exporter
